Rails.application.routes.draw do
  get 'material_lists/createMaterialList'
  post 'material_lists/createMaterialList'
  get 'material_lists/updateMaterialList'
  post 'material_lists/updateMaterialList'
  get 'material_lists/deleteMaterialList'
  get 'kondatelists/createKondate'
  post 'kondatelists/createKondate'
  get 'kondatelists/updateKondate'
  post 'kondatelists/updateKondate'
  patch 'kondatelists/updateKondate'
  get 'kondatelists/deleteKondate'
  delete 'kondatelists/deleteKondate'
  get 'kondatelists/showKondate'
  get 'menus/search'
  post 'menus/search'
  post 'menus', to: 'menus#search'
  get 'menus/edit'
  get 'menus/find'
  post 'menus', to: 'menus#find'
  post 'menus/find'
  get 'users/index'
  get 'menus/edit'
  post 'menus/edit'
  post 'menus/new'
  get 'menus/end'
  post 'menus/end'
  get 'menus/update'
  post 'menus/update'
  patch 'menus/update'
  get 'menus/new'
  post 'menus/new'
  get 'menus/add'
  post 'menus/add'
  get 'menus/delete'
  post 'menus/delete'
  delete 'menus/delete'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
